name: The Recovery Revolution
favicon: null
layout_spectrum: 0.24614
typography_spectrum: 0.35993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#71777c'
    - '#01c60e'
    - '#ff28a7'
    - '#015e07'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
