name: The Recovery Revolution
favicon: null
layout_spectrum: 0.25329335150308907
typography_spectrum: 0.25286225439049304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46068582660518587
  lightness: 0.04144180263392627
  saturation: 0.13521760166622698
  rhythmicContrast: 0.6697199263144284
purpose: []
